### ISSUE TITLE
Setting on SemEval2010_task8 dataset

### ISSUE THREAD

**Issue by HWZX** [Cartus/AGGCN#10]
I'm really grateful that you share the setting of TACRED dataset.  Would you please to share the setting of SemEval2010_task8 dataset

**Comment by GolvenLD** [comment]
I would guess that you just need to modify the loader.py script according to your database's structure. It must be possible since in the original paper, TACRED was not the only tested database :)
I am looking at a similar manipulation over here because TACRED requires special access, I'll let you know if I can get something working

**Comment by HWZX** [comment]
@GolvenLD  I'm just asking for the hyperparameter settings. I think no matter with the loader.py script.

**Comment by GolvenLD** [comment]
You might still want to take a look, all datasets don't necessarily have the same structure.

**Comment by HWZX** [comment]
@GolvenLD I have change the format as same as TACRED, so I want the hyperparameter to get the best result in paper

**Comment by DesireHope** [comment]
> @GolvenLD I have change the format as same as TACRED, so I want the hyperparameter to get the best result in paper
请问如何转换格式？想用SemEval2010_task8 做实验

**Comment by DesireHope** [comment]
请问如何转换格式？想用SemEval2010_task8 做实验

**Comment by BinbinBian** [comment]
Hi, when will you release the code for the data of n-ary relation extraction and SemEval2010_task8 ? Thanks.

**Comment by MiniiEcho** [comment]
Hello, I want to buy TACRED dataset, but it always fails. Can you share one with me? I'm willing to pay for it.

**Comment by DreamInvoker** [comment]
@MiniiEcho It seems that TACRED is a licensed data, the author or the user shall not make profit from it, you should try another way.

**Comment by waxin** [comment]
> @GolvenLD I'm just asking for the hyperparameter settings. I think no matter with the loader.py script.
Can you share your loader.py? Thank you very much. My email：wz520@mail.ustc.edu.cn

**Comment by Gabriellamin** [comment]
@waxin @DreamInvoker 请问可以分享一下TACRED数据集吗？官网上需要付费

**Comment by rsanshierli** [comment]
@HWZX Hi, can you send me a copy of your modified data set about SemEval2010_task8? I will thank you very much. My email：470294527@qq.com

**Comment by waxin** [comment]
I have uploaded the dataset and code to github [https://github.com/waxin/ToTACRED], you can view it if needed.

在2019-11-05 10:01:08，rsanshierlinotifications@github.com写道：

@HWZX Hi, can you send me a copy of your modified data set about SemEval2010_task8? I will thank you very much. My email：470294527@qq.com

**Comment by Cartus** [comment]
Model for SemEval task8 has been released, please refer to the semeval directory for the settings and the pretrained model.

**Comment by hientrannaist** [comment]
Sorry for disturbing you, but as I know, the number of classes in the SemEval2010-Task 8 is 19. (9 directed relations and a special Other class). Why the number of classes in your json semeval folder is only 10 (also in the dict LABEL_TO_ID in the file utils/constant.py)? I wonder that we are ignoring the directionality of relations?

**Comment by Cartus** [comment]
@hientrannaist answered ur question in another issue.
