### ISSUE TITLE
What method did you use to generate the dependency trees for the semeval dataset

### ISSUE THREAD

**Issue by RichJackson** [Cartus/AGGCN#19]
Hi there. Thanks for posting your code!

I'm interested in applying this methodology to other datasets. My reading of it is that you preprocess data to derive the dependency tree before training. What method did you use to do this for the Semeval dataset, as this doesn't have the dependency tree annotated in the original data?

**Comment by Cartus** [comment]
I simply used the Stanford CoreNLP parser as the one used in the TACRED dataset.
