### ISSUE TITLE
请问我怎么在semeval数据集上运行您的代码？

### ISSUE THREAD

**Issue by zlh-source** [Cartus/AGGCN#20]
您好，
我发现项目里有关于semeval的数据集和相关代码，但是在README里面并没有提及关于semeval的数据集和相关代码的任何事情。
因此，我想问一下，如果要在semeval数据集上运行您的代码，需要做哪些事情？模型在semeval数据集上的得分情况怎么样？

**Comment by Cartus** [comment]
Hi,

Readme for Semeval dataset is available:
[https://github.com/Cartus/AGGCN/tree/master/semeval](url)

Feel free to ask if it does not help.

**Comment by zlh-source** [comment]
好的，谢谢您。我刚刚已经把它运行起来了。
请问这个程序在semeval的表现如何？您有记录吗？

**Comment by Cartus** [comment]
Basically, u need to write your own preprocessing code. 

The head list means the head of the token. Here [the, system, as, described, above, has, ...] [2, 6, 2, 3, 4, 0, ...]
For example, the head of the first token "the" is index 2, which means the second token "system" is the head of "the". Similarly, the head of the token "system" is index 6, which is the token "has". The index of "has" is 0, which means it is the root node of the dependency tree.

For the usage of the Stanford CoreNLP, I suggest you to read their official document.

**Comment by zlh-source** [comment]
好的。谢谢您的回复。对我帮助很大！

**Comment by Cartus** [comment]
No problem. I will close this issue, feel free to reopen it if you have further questions.
