### ISSUE TITLE
Why the number of classes on the SemEval2010-Task 8 is only 10?

### ISSUE THREAD

**Issue by hientrannaist** [Cartus/AGGCN#24]
Hi @Cartus,
Sorry for disturbing you, but as I know, the number of classes in the SemEval2010-Task 8 is 19. (9 directed relations and a special Other class). Why the number of classes in your json semeval folder is only 10 (also in the dict LABEL_TO_ID in the file utils/constant.py)? I wonder that we are ignoring the directionality of relations?
Thank you for your consideration!

**Comment by Cartus** [comment]
Yes. Following previous work, we ignore the directionality of relations.

Makoto Miwa and Mohit Bansal. 2016. End-to-end relation extraction using lstms on sequences and tree structures. In Proc. of ACL

Yuhao Zhang, Peng Qi, and Christopher D. Manning. 2018. Graph convolution over pruned dependency trees improves relation extraction. In Proc. of EMNLP.

**Comment by hientrannaist** [comment]
Now, I understand. Thank you very much for your time!
