### ISSUE TITLE
some question about your paper

### ISSUE THREAD

**Issue by amazingYX** [Cartus/AGGCN#25]
Hello, I read your thesis recently, and I found that the formula (2) in your paper seems to be different from the algorithm in the code. In your code, calculating the attention guided adjacency matrix, the V matrix is not used, but V appears in your formula (2). If you calculate according to the formula (2) in your paper, some problems may arise in the dimensions of the data.

**Comment by Cartus** [comment]
Hi, thank you so much for pointing it out. We have made a mistake in the paper. The V matrix should be dropped. We will revise the paper accordingly.

Thank you again and sorry for the inconvenience caused.

**Comment by amazingYX** [comment]
I'm very happy that I can help you
