### ISSUE TITLE
how to get standford_head and stanford_deprel for cross-sentence data

### ISSUE THREAD

**Issue by FanY1999** [Cartus/AGGCN#31]
hello, when I tried to generate the two fields（stanford_head and stanford_deprel） with the stanfordnlp tool,and converted the result into a recognizable pattern for your code， I found a little difference between my results and yours(pubmed dataset).

for example,  the sentence"2. acquired resistance mechanism 1 ) secondary t790m mutation of the egfr gene unfortunately , many of those patient who originally had respond eventually become insensitive to gefitinib or erlotinib therapy through acquire resistance ."

my output:
![屏幕快照 2021-04-15 下午5.54.09.png](https://i.loli.net/2021/04/15/szYU1b5h2JCkavE.png)
your output：
![屏幕快照 2021-04-15 下午5.56.15.png](https://i.loli.net/2021/04/15/3oIxevLc9z5Rqri.png)

we can see that,in your output ,there're many "-1" value and "self" content.

So,I wonder how do you get the output?Is it because our tool versions are different?

**Comment by Cartus** [comment]
Hi, for PubMed dataset, we used the preprocessed data from previous work: N-ary Relation Extraction using Graph State LSTM (EMNLP2018). We did not use any other dependency parsers to get the dependency tree. I am not sure which version of the tool they used to get the result.

**Comment by FanY1999** [comment]
Thank you. 

So，can I understand your work in this way:  For the two different tasks ,namely, cross-sentence and sentence-level, except that the input content is not the same, specifically, the stanford_head field is different, and the other processing procedures are basically the same.

**Comment by Cartus** [comment]
Close this issue. Feel free to re-open it if you have further questions.
